wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1724908531
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 84
      - 98
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 84
      - 98
      3:
      - 23
      4: 3.10.8
      5: 0.17.8
      6: 4.44.2
      8:
      - 1
      - 5
      13: linux-x86_64
